_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 5
                - 53
                - 105
            "2":
                - 5
                - 53
                - 105
            "3":
                - 55
            "4": 3.11.7
            "5": 0.20.1
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
